### ISSUE TITLE
Any `admin` user can change `root` password

### ISSUE THREAD

**Issue by hbredin** [camomile-project/camomile-server#42]
It looks like any `admin` user can modify the `root` password using `PUT /user/:id_root`
If this is true, this is a major security issue.

**Comment by juandelamontana** [comment]
add this verification in the user update function : 


if (req.body.password && user.username == "root" && req.session.user.username != "root" )   error="change the password of this user is not allowed";

**Comment by hbredin** [comment]
Done in commit 329ae140132be6e7228a2600178d961b6709391a
