### ISSUE TITLE
server crash when get annotation with an id_layer null

### ISSUE THREAD

**Issue by juandelamontana** [camomile-project/camomile-server#44]
server crash when try to get annotation ACL whit an id_layer null

/app/controllers/utils.js:242
            resource.getPermissions(callback);
                     ^
TypeError: Cannot call method 'getPermissions' of null
    at /app/controllers/utils.js:242:22
    at /app/node_modules/mongoose/lib/query.js:1170:16
    at /app/node_modules/mongoose/node_modules/kareem/index.js:103:16
    at process._tickCallback (node.js:448:13)

**Comment by hbredin** [comment]
Which version of the server are you using?
It should be fixed in 0.5.4

**Comment by juandelamontana** [comment]
Ok I update the docker-compose.yml in https://github.com/camomile-project/camomile-client-python/blob/master/example/docker-compose.yml
